### ISSUE TITLE
Dotted lines are not darker in the options

### ISSUE THREAD

**Issue by pusewicz** [IlanCosman/tide#117] opened 2021-03-08 09:30 UTC
#### Describe the bug

Dotted line shades look the same.

I'm not sure which version broke it, or whether it's due to Fish being upgraded to 3.2.0. It did work before in Tide 4.0.0 and Fish 3.1.2. Running under iTerm 3.4.4. on macOS Big Sur.

#### Steps to reproduce

1. Run `tide config`
2. Go to the Connection Color step. 

#### Expected behavior

Lines should be darker in the darker options.

#### Screenshots

![Screenshot 2021-03-08 at 10 22 04](https://user-images.githubusercontent.com/940/110301647-9c8c7600-7ff8-11eb-81c6-608d39a29fa8.png)

#### Environment (please complete the following information)

- Operating System: macOS Big Sur 11.2.2
- Output of `tide bug-report`:

```console
fish, version 3.2.0
tide, version 4.2.0
xterm-256color
```

**Comment by IlanCosman** [comment] 2021-03-08 15:59
Can you try changing your color scheme to a different preset (just for testing purposes 😄)? I'm quite confident the code is working.

**Comment by pusewicz** [comment] 2021-03-08 17:01
Does not make any difference. But! I tested the line, and it does indeed change the shade as expected:

![image](https://user-images.githubusercontent.com/940/110354328-548d4380-8038-11eb-85f2-dd2685c8e927.png)

**Comment by IlanCosman** [comment] 2021-03-22 21:05
Closing this because I'm 99.99% sure that the code is working. I can't reproduce, though my brother ran into this a while back. This is probably some sort of graphical bug that's unrelated to Tide. Thanks for filing @pusewicz 😄

**Closed by IlanCosman** 2021-03-22 21:05 UTC
Labels: 🐛 bug
