### ISSUE TITLE
Prompt Lag?

### ISSUE THREAD

**Issue by cwagdev** [IlanCosman/tide#176] opened 2021-07-14 16:52 UTC
I updated to the latest versions of tide and fish yesterday and now I am seeing lag at the prompt, specifically it takes a little time for the prompt to update with the cwd... it's very minimal but wasn't like this before, is there something I can look into to fixing it or is this a known issue?

tide, version 4.3.4
fish, version 3.3.1

https://user-images.githubusercontent.com/235322/125661479-ec82bfb6-4c52-4155-b696-33b95b9e8b13.mp4

**Comment by IlanCosman** [comment] 2021-07-14 18:11
I'm experiencing this on Arch Linux, but not on macOS (at least that I can tell). Maybe it's time for async to go 😞

**Comment by cwagdev** [comment] 2021-07-14 18:13
I am on macOS 11.4 using with iTerm2 v3.4.8 FWIW

**Comment by kidonng** [comment] 2021-07-15 12:58
That update delay looks indeed a little longer than expected but IMO still accessible. What's the result with only tide and nothing else?

> Maybe it's time for async to go 😞

Please don't. This is the only thing that makes tide so awesome (I'd really like to see a equivalent of  p10k in fish). If tide becomes synchronous I don't see a reason to use more feature-rich ones like Starship.

**Comment by matan129** [comment] 2021-07-19 11:13
Perhaps it'd be a good idea to allow some items to be synchronous while other will remain async?
(For example, the `pwd` item surely can be sync.)

**Comment by kidonng** [comment] 2021-07-20 06:27
That would be awesome, but unfortunately not possible in tide's current state.

**Comment by vesche** [comment] 2021-08-04 17:10
I'm also having this issue, macOS Big Sur 11.5.1 / iTerm2 v3.4.8 / fish v3.3.1 / tide v4.3.4 (all latest as of writing this). Removing tide fixes the problem. Unfortunately, this is breaking to my workflow and I'll have to stop using tide for now. I'm often moving fast in the CLI and the results with this pwd delay are often confusing to me. See the example below.

![2021-08-04 11 59 47](https://user-images.githubusercontent.com/8083281/128223355-6b83873c-56c1-47e6-9fe7-299e10362623.gif)

**Comment by kidonng** [comment] 2021-08-05 05:00
That looks even worse than the OP. Repeat my question: What's the result with only tide and nothing else?

Also can anyone with issue test latest fish master because it may be related to #171.

**Comment by vesche** [comment] 2021-08-05 06:37
I tested with the latest [development build](https://github.com/fish-shell/fish-shell/wiki/Development-builds) (3.3.1-168-g5e46ad645) and the issue persists for me.

Downgrading to tide v2.5.0 fixes the issue (pre-async).

> What's the result with only tide and nothing else?

I'm not exactly sure what you mean by that, but I'm testing with only fisher and tide installed. I can test something else if I'm misunderstanding.

**Comment by kidonng** [comment] 2021-08-06 09:28
Thanks for the info, so there is something else going on here.

> I'm not exactly sure what you mean by that, but I'm testing with only fisher and tide installed. I can test something else if I'm misunderstanding.

That's it，sorry if I'm not being clear.

**Comment by IlanCosman** [comment] 2021-08-06 15:03
This issue is, in fact, a Fish bug. I opened a report here: https://github.com/fish-shell/fish-shell/issues/8209

Please do not comment there unless you have something substantive/new to add.

**Comment by pvsmpraveen** [comment] 2021-09-25 14:33
> Yah, I'm experiencing this very slight lag on Arch Linux, but not on macOS (at least that I can tell). Maybe it's time for async to go 😞
Same experience with Linux and MacOS

**Comment by IlanCosman** [comment] 2021-09-25 14:43
This is fixed in the upcoming Fish 3.4 🙂

**Comment by dabeeeenster** [comment] 2021-12-09 23:45
Hmm - I just compiled `master` branch of fish-shell on MacOS, but I'm seeing lag.

**Comment by IlanCosman** [comment] 2021-12-09 23:49
@dabeeeenster I can't reproduce, and that really shouldn't be the case 🤷‍♂️ sorry 😞

**Comment by svenihoney** [comment] 2022-01-02 13:02
I also have the lag, see https://asciinema.org/a/459511.

I would expect that the directory is changed immediately and the branch information updated asynchronously. The lag is visible even if the directory change is done between directories without git repositories inside.

**Comment by IlanCosman** [comment] 2022-01-02 15:24
@svenihoney That's not the lag, that's Tide working as currently coded. The directory is updated asynchronously just like everything else. This should probably changed though.

**Comment by svenihoney** [comment] 2022-01-02 15:34
Okay, my bad. But this is exactly the point that keeps me from using tide currently - I simply don't like jumping input cursors on the screen...it doesn't matter for changing branch names, which occurs rarely. But during traversal of directory trees it is unusable for me...

**Comment by IlanCosman** [comment] 2022-03-14 00:33
Alright this should be fixed by Fish 3.4 😄

**Closed by IlanCosman** 2022-03-14 00:33 UTC
Labels: 🐛 bug, 🏞️ upstream
