### ISSUE TITLE
Last character in the first line of a two line prompt is missing

### ISSUE THREAD

**Issue by nuxencs** [IlanCosman/tide#462] opened 2023-11-18 14:25 UTC
#### Describe the bug

When opening a new terminal window or tab, the last character of the first line will not be rendered.

#### Steps to reproduce

1. Open a new terminal window or tab (tested in WezTerm, Windows Terminal, JetBrains integrated terminal)
2. Configure Tide to use a two line prompt
3. Tide doesn't render the last character of the first line

#### Screenshots

- Prompt missing the last character in the top line, in this case seconds:
![Screenshot 2023-11-18 150854](https://github.com/IlanCosman/tide/assets/47067662/cde4fe68-a21b-4d76-bb6a-36d699c5eadd)
- Not happening with single line prompt:
![Screenshot 2023-11-18 151037](https://github.com/IlanCosman/tide/assets/47067662/ee9d2dd9-3aa2-433f-82bb-3555f8c2ca87)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1
tide version: 5.6.0
term: xterm-256color
os: WSL Ubuntu 22.04.3 LTS
terminal emulator: WezTerm
fish startup: 7.56 millis
fisher plugins: jorgebucaran/fisher meaningful-ooo/sponge ilancosman/tide@v5 dracula/fish jorgebucaran/autopair.fish
```

#### Additional context

```text
OS Name: Microsoft Windows 11 Pro
Version: 10.0.22631 Build 22631
```

**Comment by IlanCosman** [comment] 2023-11-18 14:31
Duplicate of #310

**Closed** 2023-11-18 14:32 UTC
Labels: 🐛 bug
