### ISSUE TITLE
Prompt directory path does not update after cd 

### ISSUE THREAD

**Issue by mjparker** [IlanCosman/tide#109] opened 2021-03-02 00:07 UTC
#### Describe the bug

The prompt directory path does not update after `cd` 
See below

#### Steps to reproduce

![CleanShot 2021-03-01 at 19 02 42](https://user-images.githubusercontent.com/1706734/109576057-108ec180-7ac1-11eb-9907-c48ede2bd097.gif)

#### Expected behavior

After running cd repos, next line will print `~/repos >` at prompt

#### Environment (please complete the following information)

- Operating System: macOS 11.2.1
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 4.1.1
xterm-256color
```

**Comment by mjparker** [comment] 2021-03-02 01:09
Gave that a shot, same issue: 
![CleanShot 2021-03-01 at 20 07 42](https://user-images.githubusercontent.com/1706734/109581298-0de49a00-7aca-11eb-848f-0a14c6d16c53.gif)

**Comment by IlanCosman** [comment] 2021-03-02 01:57
Well darn. I've only ever gotten gotten [one other report](https://github.com/IlanCosman/tide/issues/72#issuecomment-763133022) of this this issue happening on 3.1.2. It may be that it's some really rare bug. All I can say is sorry and that I hope Fish 3.2 fixes it 😞

**Comment by mjparker** [comment] 2021-03-02 03:19
Yeah, I am at a loss here. I performed the same installation steps on two other machines and Tide works just fine. 

On this machine, I burned everything down, installed 3.2, and it still breaks after installing Tide. Need to give up for the night but tomorrow may try to see if I can get some information out of my system logs

**Comment by IlanCosman** [comment] 2021-03-03 20:57
I can now reproduce this (unwillingly) on my Arch VM as usual, it's an issue with universal variables being abused 😂

**Comment by IlanCosman** [comment] 2021-03-03 21:40
Okay, this is _probably_ solved in Fish 3.2.1: https://github.com/fish-shell/fish-shell/issues/7774

**Comment by IlanCosman** [comment] 2021-03-18 20:45
@mjparker Closing because this should be fixed. If it's not please reopen. Thanks for reporting this bug 😄

**Closed by IlanCosman** 2021-03-18 20:45 UTC
Labels: 🏞️ upstream, 🐛 bug

**Comment by mrvkino** [comment] 2021-04-15 19:17
I have the same issue with:
```
❯ fish --version
fish, version 3.2.1
```

Here is the behaviour, I have skipped the configuration:


https://user-images.githubusercontent.com/279511/114925395-0b7d9b80-9dfd-11eb-9234-fca71a55d769.mov

**Comment by mrvkino** [comment] 2021-04-15 20:25
I have the issue with the latest fish version

```
fish version: 3.2.2
tide version: 4.3.4
term: xterm-256color
os: MacOS 11.2.3
terminal emulator: Iterm
```

Here is the behaviour. I had to press enter to show the first prompt. The same delay happens when I hit `ctrl+c` the interrupt icon appears if I press enter.

I skipped the config in the video:

https://user-images.githubusercontent.com/279511/114933782-13423d80-9e07-11eb-8bdf-4ff0ce6b9908.mov

**Comment by IlanCosman** [comment] 2021-04-15 20:43
@mrvkino I don't know what to tell you, sorry 😞 I can't reproduce on my machines, mac or otherwise. This should have been fixed in 3.2.1 🤷‍♂️

**Comment by mrvkino** [comment] 2021-04-17 02:52
This "asynchronous" behaviour seems to be using the universal variable and the `--on-variable` flag to update the prompt.
How does Tide knows to wait for all the value to update?

I am trying to debug Tide on my machine to figure out this issue. I couldn't find a test validating the prompt update after a directory change (maybe I didn't see it). While running the test suite I had a couple of failures because of colouring (I think):
```
Failure in tests/_tide_item_pwd.test.fish:

  The CHECK on line 31 wants:
    ~

  which failed to match line stdout:6:
    \xf015 ~

  Context:
    [...] from line 23 (stdout:3):
    /
    /usr
    /usr/share
    \xf015 ~ <= does not match CHECK '~' on line 31
    \xf07c ~/normal <= does not match CHECK '~/normal' on line 32
    \xf07c ~/normal/dir <= does not match CHECK '~/normal/dir' on line 33
    \xf07c ~/a/b/c/d/e/f/g/hotel/india/juliett/kilo/lima/mike/november/oscar/papa <= does not match CHECK '~/a/b/c/d/e/f/g/hotel/india/juliett/kilo/lima/mike/november/oscar/papa' on line 41
    \xf07c ~/a/brav/c/d/e/f/g/h/india/juliett/kilo/lima/mike/november/oscar/papa <= does not match CHECK '~/a/brav/c/d/e/f/g/h/india/juliett/kilo/lima/mike/november/oscar/papa' on line 45
    \xf07c ~/alfa/b/c/d/e/f/g/h/india/juliett/kilo/lima/mike/november/oscar/papa <= does not match CHECK '~/alfa/b/c/d/e/f/g/h/india/juliett/kilo/lima/mike/november/oscar/papa' on line 50

  when running command:
    fish tests/_tide_item_pwd.test.fish
```

Is this normal or could be an indication of some borked setup?

**Comment by IlanCosman** [comment] 2021-04-17 14:46
That shouldn't have anything to do with this problem, and yah there is a severe lack of integration tests.

Try running these interactively:

```fish
function fish_prompt
    fish --command "sleep .1; set -U prompt_var (pwd)" &
    echo $prompt_var
end

function prompt_repaint --on-variable prompt_var
    commandline --function repaint
end
```

If that doesn't work for you, then it's not a Tide problem.

**Comment by mrvkino** [comment] 2021-04-18 03:30
Hum! This is throwing me for a loop. I have the same issue with your sample code.

I also tried:

```fish
function fish_prompt
    fish --command "sleep .1; set -U prompt_var (pwd)" &
    echo $prompt_var
end

function prompt_repaint --on-variable prompt_var
    echo ALLO; commandline --function repaint
end
```

I get this:
```fish
❯ function fish_prompt
          fish --command "sleep .1; set -U prompt_var (pwd)" &
          echo $prompt_var
  end
/Usersfunction prompt_repaint --on-variable prompt_var
              echo ALLO; commandline --function repaint
      end
/Users
/Users
/Users
/Users
/Users
/Users
/Users
/Userscd mrogersvallee/
/Users
ALLO
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
/Users/mrogersvallee
```

It looks like the repaint function is called on the second enter after a change of directory only.

The following worked (I reversed the print and set to emulate the command finishing after the print):
```fish
function fish_prompt
    echo $prompt_var
    sleep 1
    set -U prompt_var (pwd)
end

function prompt_repaint --on-variable prompt_var
    commandline --function repaint
end
```

result:
```fish
❯ function fish_prompt
          echo $prompt_var
          sleep 1
          set -U prompt_var (pwd)
  end
/Users/mrogersvallee
/Users/mrogersvalleecd ..
/Users/mrogersvallee
/Usersfunction prompt_repaint --on-variable prompt_var
              commandline --function repaint
      end
/Userscd mrogersvallee/
/Users/mrogersvalleecd ..
/Users
```

https://user-images.githubusercontent.com/279511/115132989-ca3ee480-9fd2-11eb-9413-eb34f0e84927.mov

Before the prompt_repaint, I had the same behaviour as before. The data is updated to late. When I add the repaint, I have the behaviour expected. This seems to indicate that the `fish --command ... &` is not signalling that the variable has been updated correctly.

Reading the following issues in the fish repo made me question if I am just unlucky (hope not!):
https://github.com/fish-shell/fish-shell/issues/7671 <= not working for me
https://github.com/fish-shell/fish-shell/issues/7260 <= working for me

Does any of this make sense?

**Comment by IlanCosman** [comment] 2021-04-18 03:42
Thanks for the info Michel! I appreciate you putting in effort to try to debug--most people just say it isn't working and storm off 😄 

Unfortunately I don't know where to go from here. If the sample code isn't working then it's a Fish/your machine problem. 

Perhaps you could submit an issue to the Fish repository 🤷‍♂️

By any chance, does https://github.com/jorgebucaran/hydro work for you?

**Comment by mrvkino** [comment] 2021-04-19 03:26
My pleasure! It's the least I can do for a project I am using and would like to become even better.

I have another good one for you. I tried [hydro](https://github.com/jorgebucaran/hydro) and I saw I had partial asynchronous update. I had the branch name update on the current prompt but not the status (I still needed to do another enter to get it to show).

This got me thinking and I looked in his code and I saw he made multiple assignation to the universal variable `$_hydro_git` (the variable used to trigger the repaint). If I got two variable update I might get the behaviour I want.

I used the following:
```fish
function fish_prompt
    fish --command "sleep .1; set -U prompt_var (pwd)'ALLO'; set -U prompt_var (pwd)" &
    echo $prompt_var
end

function prompt_repaint --on-variable prompt_var
    commandline --function repaint
end
```

https://user-images.githubusercontent.com/279511/115175550-2e2be080-a099-11eb-91ef-5f1fefe5eb1f.mov

This gave me a behaviour that was close to what I want. An updated prompt pwd (also notice the pwd with `ALLO` does not show on the terminal). But If you look in the window title, you can see the process active (fish or sleep) changing rapidly. These are the exact command created by the `fish_prompt` function. This made me look closer to the handshake between the the `fish --command` and the `prompt_repaint`.

I tried you original sample code (https://github.com/IlanCosman/tide/issues/109#issuecomment-821834033) with iTerm instead of terminal (iTerm is a bit more pedantic with my config).

https://user-images.githubusercontent.com/279511/115175718-84008880-a099-11eb-8cec-17fb61d501f3.mov

At the last step I did a `ctrl+d`. The background command is not finishing and this does not cause a repaint. Then I remembered that resizing the window update the repaint in fish. Then I tried the following in iTerm again.

https://user-images.githubusercontent.com/279511/115176440-19e8e300-a09b-11eb-84fc-a23805926f3d.mov

By resizing the window, I trigger the repaint as expected. I did a `ctrl+d` again, but this time the terminal did not have a pending process. So it seems the `--on-variable` is not triggering on the variable update and lock the `fish --command`. If we force a `repaint` this will unblock the process and everything is back to normal. And who knows what is happening when I am doing the double `set` of the first example.

I think fish repo will have another bug report regarding async prompt and repaint. 😂
I just have to figure out how to TLDR this thread.

**Comment by mrvkino** [comment] 2021-04-20 01:38
You might want to know, I found a workaround that "works".

I added the following in my config.fish. ( the symbol is just to know if it is working )
```fish
# This is here because I need to force a repaint for TIDE
function _tide_item_second_repaint
    set_color white
    echo -n "ø"
    fish --private --interactive --command "commandline --function repaint"
end
set -g -a tide_right_prompt_items newline second_repaint
set -g tide_second_repaint_bg_color $tide_context_bg_color
```

https://user-images.githubusercontent.com/279511/115323859-dbb0f980-a156-11eb-8b8f-df305d69fcf4.mov

It refreshes the prompt and also whenI I kill the terminal I do not have the unfinished process. But, if I press enter many times too fast I will get broken Pipe message sometime, probably because I am interrupting the `fish --command`. But, I call that a win in my book anyway.

**Comment by fipso** [comment] 2021-07-25 11:06
Having the exact same issue running Arch Linux in WSL + Windows Terminal
