### ISSUE TITLE
Kitty launch in current working directory doesn't work with tide

### ISSUE THREAD

**Issue by MrHighTech** [IlanCosman/tide#262] opened 2022-03-10 21:51 UTC
#### Describe the bug

While having Tide installed kitty shortcut to launch the terminal in the same working directory doesn't work
```launch --cwd=current```

#### Steps to reproduce

1. install tide
2. add ```map alt+shift+enter launch --cwd=current``` to the kitty config
3. kitty doesn't launch in the current working directory, it launches in home directory

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-kitty
os: 5.16.13-arch1-1
terminal emulator: Kitty
```

**Comment by IlanCosman** [comment] 2022-03-11 17:38
Yah I can reproduce. It's some sort of fish/kitty bug, because this reproduces it with `fish, version 3.3.1-1098-g3a23fdf35`:

```fish
function fish_prompt
    sleep .1 &
    builtin disown
    prompt_pwd
end
```

I'm going to close this as upstream, because there's nothing to be done on Tide's side of things.

**Closed by IlanCosman** 2022-03-11 17:38 UTC
Labels: 🐛 bug

**Comment by milkias17** [comment] 2022-03-12 22:07
Can you elaborate on how this is upstream issue as base fish and other prompts handle this correctly?

**Comment by IlanCosman** [comment] 2022-03-12 22:11
The bug is reproduced the `fish_prompt` code above. The code merely spawns and disowns a process, and then prints out pwd. 

Therefore the bug clearly is not caused by any of Tide's complexities, but rather by the interaction of fish spawning+disowning processes and the way kitty gets the pwd.
