### ISSUE TITLE
Add loading indicator to show when prompt is out of date

### ISSUE THREAD

**Issue by gblock0** [IlanCosman/tide#82] opened 2021-01-24 17:45 UTC
#### Describe the bug

My gut is telling me that a new prompt is being shown before the background jobs are done. That in of itself is great, but there is no feedback to the user that those background jobs are still executing. What I'm seeing is the new prompt looks exactly the same as the previous prompt until the background processes complete, and then the new prompt updates.

#### Steps to reproduce

1. Press `enter` on an empty prompt or try to execute an unknown command.

The prompt shows inaccurate information until background jobs are complete. i.e. the time is wrong or the `x 127` does not show up.

#### Expected behavior

Some kind of feedback that the prompt is updating. Maybe `...` or something like that?

#### Screenshots

Here is a screencast I took. Take note of the time not changing for a second after each time I press `enter` or the `x 127` not showing up for a second after I try to execute an unknown command.

https://user-images.githubusercontent.com/1434705/105638570-193c0a00-5e28-11eb-982d-d2f8ce9e2091.mov

#### Environment (please complete the following information)

- Operating System: macOS 10.15.7
- Output of `tide bug-report`:

``` console
fish, version 3.1.2
tide, version 3.2.0
screen-256color
```

#### Additional context

I'm using tmux in Alacritty. I was also able to reproduce this outside of tmux and in iTerm2.

**Comment by IlanCosman** [comment] 2021-01-24 17:59
Wow, that is a very thorough ticket 😄 Yes, the old prompt is shown while the new prompt is calculated in the background. I'd say this ticket is an enhancement instead of a bug, because it's working as intended right now.

Displaying out of date information without warning the user is certainly not preferred. When the prompt is slow, the current behavior is bad. However, I think that a loading indicator might increase the "flicker" you get when changing directories when the prompt is fast.

Either way, this deserves some thought, and actually implementing an indicator would be a fair bit of work to do right. It's on the radar, but not a top priority because the current behavior is not very bad--it only takes a fraction of a second to update anyway, so it's kind of no harm no foul.

Thanks for reporting 😄

**Comment by gblock0** [comment] 2021-01-24 18:12
Np! Yea, it's not a huge deal, but was bugging me enough to write up a ticket haha.

Just spitballing, maybe have a configuration that allows a user to specify which parts of the prompt can be async, which would default to the entire prompt? Then, for example, the user could say that they _only_ want the git section to be async?

Thanks for all your hard work. It's really appreciated!

**Comment by IlanCosman** [comment] 2021-01-24 18:16
Yah I've thought of making it selectively async, but honestly that seems really difficult for very little gain. The only reasonable options I think are full async like now, or just git async. Maybe just git is the right choice to reduce prompt flicker. Idk.

**Comment by mattgreen** [comment] 2021-02-11 20:10
> Maybe just git is the right choice to reduce prompt flicker

I've tried several variations of this, and I arrived at this conclusion. 

Other prompts tout how everything is asynchronous, but it doesn't really amount to much from a user perspective. It's arguably worse, due to more text flickering, and the complexity it inflicts on the code. Keep in mind that the deadline for initial rendering of the prompt is the monitor refresh rate (16ms at 60hz, 6.9ms at 144hz), which is a lot of time. If you finish in 2ms, it still won't show up for another 14ms for most people.

UX > microbenchmarks

**Comment by IlanCosman** [comment] 2021-02-11 22:30
16 ms isn't a lot of time at all.

On my M1 Macbook Air in the home directory (in ms):

- Default prompt: 19
- Pure: 25
- Tide: 26
- Bobthefish: 21
- Starship: 12

Even if I asyncified git, we still wouldn't be under 16ms. And there are other items I didn't factor into that original calculation. `date` takes 4ms, and `rustc --version` takes probably 20ms, though that one is off by default. There are also items can become slow. For example, PWD can take 20ms in a long directory (even lucid.fish took 10ms here).

You're taking a lucid.fish perspective to the issue that doesn't really apply.

**Comment by IlanCosman** [comment] 2021-04-27 21:45
Closing because I don't plan to add this. The main shell doesn't know which parts of the string are which item, so there's no elegant way to implement this such as dimming the git branch name.

Tide has also gotten significantly faster in the past few months, and v5 should hopefully be a speed bump as well. So there's even less value to doing this than before.

**Closed by IlanCosman** 2021-04-27 21:45 UTC
Labels: 🌊 enhancement
