### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by pangwalla** [IlanCosman/tide#22] opened 2020-09-03 17:58 UTC
Getting an error on initial install.  Have wiped fish config directory twice, purged through apt, and on install again am getting this:

```bash
> curl -sL git.io/tide | source && tide_install
Installing tide theme...
math: Expected at least 1 args, got 0
math: Expected at least 1 args, got 0
Tide theme installed!

Configure tide prompt? [Y/n]
```

These errors persist each time the shell is run.  Before the fish greeting I see this same error.  The prompt customizations work fine however, so not a devastating issue obviously.

Install on Debian using testing repo.

**Comment by IlanCosman** [comment] 2020-09-03 18:28
Hi @pangwalla, thanks a lot for submitting a report 😄 For the future it would be nice if you would use the issue templates that request some standard information.

I can't reproduce this issue on Ubuntu 20.04 VMs with fish versions `3.1.0` or `3.1.2` using the latest version of Tide. What version of `fish` are you running? If it's older than 3.1.0 then it will not work.

**Comment by pangwalla** [comment] 2020-09-03 18:45
Yes, sure I apologize.  Fish version is 3.1.2-3

**Comment by IlanCosman** [comment] 2020-09-03 20:36
Ah wow ok I didn't expect a beta version of fish 😂 I couldn't find a fish version 3.1.2-3 so I installed the latest [nightly](https://launchpad.net/~fish-shell/+archive/ubuntu/nightly-master), `fish, version 3.1.2-1290-g306299464`. I still can't reproduce the error on my Ubuntu 20.04 install so perhaps it's something with the debian repos. 

Regardless, given that the issue relates to a beta version of fish (which is thus unsupported by Tide) and that I can't reproduce the error, I'm going to close this issue. I definitely appreciate you filing the issue though! 😄 If there turns out to be an bug when fish 3.2 drops, I'll deal with it then.

**Closed by IlanCosman** 2020-09-03 20:36 UTC
Labels: 🐛 bug
