### ISSUE TITLE
Tide doesn't handle paths correctly

### ISSUE THREAD

**Issue by milkias17** [IlanCosman/tide#264] opened 2022-03-12 22:04 UTC
#### Describe the bug

I am unable to say what/how exactly is wrong with the way tide does paths but, I run kitty and they have an option to open a new tab with the current directory you are in. This feature doesn't work with tide. I removed tide and tried it, it works. I tried it using another fish prompt plugin and it works.
#### Steps to reproduce

1. Go to any directory like /etc or whatever directory you may like.
2. Type the keybinding(f2) you defined inside kitty, put this in kitty config(map f2launch --cwd=current --type=tab).
3. New tab opens inside home directory like a new shell instead of the current working directory

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.4.0
tide version: 5.0.1
term: xterm-kitty
os: Arch Linux
terminal emulator: kitty
```

**Comment by IlanCosman** [comment] 2022-03-12 22:05
duplicate of https://github.com/IlanCosman/tide/issues/262

**Closed by IlanCosman** 2022-03-12 22:05 UTC
Labels: 🐛 bug
