### ISSUE TITLE
When i switch to certain directories it starts outputting double prompt

### ISSUE THREAD

**Issue by hardikdangar** [IlanCosman/tide#252] opened 2022-02-19 06:54 UTC
#### Describe the bug

When i cd into laravel project directory it starts outputting prompt twice. see image https://i.imgur.com/V4IdtxN.jpeg for explanation. first  (top part of image is without double prompt and second is after switching to laravel directory. see how it starts showing prompt twice. i have reinstalled and removed both fish directory which in my case it is ~/.config/.fish/ which i deleted it and reinstalled both fish and tide and issue persists after that as well.

#### Steps to reproduce

1. open terminal
2. cd into any laravel project directory
3. see double prompt

#### Screenshots

(https://i.imgur.com/V4IdtxN.jpeg)

#### Environment

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: ubuntu 20.04
terminal emulator: gnome terminal
```

**Comment by IlanCosman** [comment] 2022-02-19 16:07
Sorry, I can't reproduce 😞

**Comment by IlanCosman** [comment] 2022-03-13 21:09
Closing b/c couldn't reproduce, new fish is out, and new tide will be out soon.

**Closed by IlanCosman** 2022-03-13 21:09 UTC
Labels: 🐛 bug
