### ISSUE TITLE
VSCode font spacing/clipping issue

### ISSUE THREAD

**Issue by chinesehemp** [IlanCosman/tide#302] opened 2022-05-11 19:56 UTC
#### Describe the bug

In VSCode the character spacing in the prompt looks to be different from Terminal and iTerm2 running on MacOS 12.3.1
#### Steps to reproduce

1. Install Tide on MacOS
2. Run VSCode
3. See spacing difference between VSCode/Terminal/iTerm2

### VSCode
<img width="835" alt="Screenshot 2022-05-11 at 20 49 56" src="https://user-images.githubusercontent.com/58605231/167934864-5414d524-c49c-4ce4-bc2f-a1231b4a69bc.png">

### Terminal
<img width="807" alt="Screenshot 2022-05-11 at 20 54 15" src="https://user-images.githubusercontent.com/58605231/167934950-1b93d789-164f-48f0-861b-a01f8268cef1.png">

### iTerm2
<img width="797" alt="Screenshot 2022-05-11 at 20 54 01" src="https://user-images.githubusercontent.com/58605231/167934897-093df227-85a5-4bc3-b7da-16cd51fb8a72.png">

#### Environment

```
fish version: 3.4.1
tide version: 5.3.0
term: xterm-256color
os: macOS 12.3.1
terminal emulator: VSCode
fish startup: 9.52 millis
fisher plugins: jorgebucaran/fisher IlanCosman/tide@v5
```

#### Additional context

See how the icons are clipped in VSCode but are okay in Terminal and iTerm2

**Comment by IlanCosman** [comment] 2022-05-11 20:00
Are you using the same font in VSCode as in the other two? 
That's all that I can think of. It's certainly not a Tide bug, as you can see Tide is printing the correct thing.

**Comment by chinesehemp** [comment] 2022-05-11 20:56
I'm using Hack Nerd Font in both.

**Comment by chinesehemp** [comment] 2022-05-11 21:02
Just tried MesloLGS NF and here's the result. Looks about the same.
<img width="451" alt="Screenshot 2022-05-11 at 22 02 21" src="https://user-images.githubusercontent.com/58605231/167947108-fd4a2e14-6de0-4ad0-8efb-256e5a8520a4.png">

**Comment by IlanCosman** [comment] 2022-05-11 22:17
Hmm yah, I can reproduce with P10K and MesloLGS NF. I'll open an issue there. Closing because it is an upstream problem 🙂

**Closed by IlanCosman** 2022-05-11 22:17 UTC
Labels: 🐛 bug

**Comment by chinesehemp** [comment] 2022-05-12 11:50
Thank you.
