### ISSUE TITLE
Vscode terminal emulator strange prompt behavior

### ISSUE THREAD

**Issue by Sniper10754** [IlanCosman/tide#443] opened 2023-09-24 10:05 UTC
#### Describe the bug

In the Vscodium terminal, the prompt is truncated in half, when a command is typed in the terminal, the right prompt is shown in a newline (it shouldnt because i set it to be a 1 line prompt)

#### Steps to reproduce

Configure your prompt to be one line
Open Vscode
Open a terminal

#### Screenshots

![image](https://github.com/IlanCosman/tide/assets/74132494/86b40f6c-272c-4b80-a0fe-a49d225e576d)
![image](https://github.com/IlanCosman/tide/assets/74132494/ef7c2bb7-7cb8-490f-b277-b20cd2fc2be7)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1
tide version: 5.6.0
term: xterm-256color
os: Arch Linux
terminal emulator: Vscode terminal emulator
fish startup: 5.42 millis
fisher plugins: ilancosman/tide@v5
```

#### Additional context

Prompt shows normally on other terminal emulators

**Comment by askiiart** [comment] 2023-10-08 23:47
Duplicate of #433

**Closed** 2023-10-08 23:49 UTC
Labels: 🐛 bug
