### ISSUE TITLE
Git doesn't show up even when added to tide_left_prompt_items

### ISSUE THREAD

**Issue by cainy-a** [IlanCosman/tide#137] opened 2021-04-02 13:58 UTC
#### `tide bug-report`
```
fish, version 3.2.1
tide, version 4.3.2
xterm-256color
```

#### Describe the bug

Git status does not show on my prompt when in a repo. my left prompt items include git (`os pwd git newline`), but the status still does not show.

#### Steps to reproduce

1. Make sure `tide_left_prompt_items` contains `git`
2. Go to a git repository
3. Prompt will not have git status

#### Screenshots

![image](https://user-images.githubusercontent.com/19270622/113421588-475b3e80-93c3-11eb-9b9f-61b758345992.png)

#### Environment

- Operating system: Debian 10 (WSL)
- Terminal emulator: Windows Terminal

#### Additional context

**Comment by IlanCosman** [comment] 2021-04-02 14:07
Duplicate of https://github.com/IlanCosman/tide/issues/114. Your git version doesn't have `git branch --show-current`. Git 2.22 (which introduced `git branch --show-current`) came out almost 2 years ago. Debian is just that slow I guess, sorry 😞

**Closed by IlanCosman** 2021-04-02 14:07 UTC
Labels: 🐛 bug

**Comment by cainy-a** [comment] 2021-04-02 14:11
Fair enough. Debian's `python` package is py 2 so yeah debian just gets slow updates. Thanks though!

**Comment by cainy-a** [comment] 2021-04-02 22:35
Update: changed to Fedora Remix WSL and working perfectly :)
![image](https://user-images.githubusercontent.com/19270622/113458976-0e938780-940c-11eb-9428-afb7c7390829.png)

**Comment by SaswatPadhi** [comment] 2021-05-17 06:59
Late to the party, but FWIW, you could also upgrade `git` from the `buster-backports` channel, which has 2.29 available:

```shell
$ sudo apt install git/buster-backports
```

Works as expected :)

@IlanCosman Would it be possible to keep an error log for items that fail to render(if there isn't one already)? It would be super helpful to check system config and report possible bugs, if we could inspect failures.

**Comment by IlanCosman** [comment] 2021-05-17 15:13
> Would it be possible to keep an error log for items that fail to render

I don't think so. How would we distinguish "failure" versus normal not-rendering?

The most obvious example is this issue itself. We use `git branch --show-current 2>/dev/null` to tell whether we are in a git repo or not. That line is expected to fail most of the time. So we'd have to check if the error is a different one than we expect (such as that the command doesn't even work because git is too old).

**Comment by SaswatPadhi** [comment] 2021-05-18 02:07
> I don't think so. How would we distinguish "failure" versus normal not-rendering?

Hmm, I thought about it a bit more and I think we may be able to distinguish. For each item, we would basically have 3 possible states:
- A _no_ failure (or success), then there is nothing to be logged
- A _soft_ failure (or expected failure), then we do not need to log the error
- A _hard_ failure (or unexpected failure), then the error _must be_ logged for the user to inspect

In this specific case, i.e. for `git branch --show-current 2>/dev/null`, we have these 3 states:
- _no_ failure when exit code is `0`
- _soft_ failure when exit code is `128`, which corresponds to "not in a git repository"
- _hard_ failure when any other exit code or `git` command was not found: because the command should always either succeed or indicate that we are not in a `git` repo. If `git` is not installed, then the user should in fact disable the `git` item entirely.

For most items, I think just checking if the exit code is `0` should be enough for asserting "_no_ failure" state.

All cases when a command, such as `git` or `nvm`, is not found on the system should be treated as "_hard_ failures" so users can inspect the logs and then disable the item entirely. This might even slightly improve the performance.

**Comment by IlanCosman** [comment] 2021-05-18 04:10
Hmm, yeah, I did forget about exit codes didn't I 😅

Basically I think it's just not worth doing. In general things don't just fail outright, and if they do they often print errors to the screen. Not worth the effort/code complexity/performance penalty.
